### ISSUE TITLE
Replace TaskCondition w/ a Channel

### ISSUE THREAD

**Issue by quinnj** [Drvi/ChunkedCSV.jl#30]
We use a custom `TaskCondition` struct [here](https://github.com/Drvi/ChunkedCSV.jl/blob/ba5df58b724d5e67d4c2beedac796817abdfcfc8/src/ChunkedCSV.jl#L73), but we basically use it to reimplement a Channel in most of the functionality.

I think it'd be cleaner to use a `Channel{Nothing}(Inf)` and it would work as follows:
* Add a `ntasks::Int` field to ParsingContext; we don't need to worry about locking/guarding this because only the lexer task will get/set it
* Change ParsingContext.cond to `tasksync::Channel{Nothing}`
* `setup_tasks!` sets `ParsingContext.ntasks` to the # of expected tasks
* `task_done!` from a consumer calls `put!(ctx.tasksync, nothing)`
* Then we have the following (default) implementation of `sync_tasks`

```julia
function sync_tasks(consume_ctx::AbstractConsumeContext, parsing_ctx::ParsingContext)
    while parsing_ctx.ntasks > 0
        take!(parsing_ctx.tasksync)
        parsing_ctx.ntasks -= 1
    end
end
```
PR showing this here: https://github.com/Drvi/ChunkedCSV.jl/pull/29

**Comment by Drvi** [comment]
Thanks for looking in to it! I think a `Channel` is pretty close, apart from the second `Conditon` and a `Vector` which we don't need. I think `push!(c, nothing)` to signal work done is not super intuitive for the user, the API I had in mind was to add `inc!(t, n::Int)`, `dec!(t, n::Int)`, `wait(t)` and `close(t, e::Exception)` methods to `TaskCondition`  which would mostly copy the current implementation (`inc! ~ setup_tasks!`, `task_done! ~ dec!`, `wait ~ sync_tasks`, `close` would be the error handling we do in `process_and_consume_task`) -- so the default implementations would be one liners mostly and the user would then have nice abstractions to use when overriding those. What do you think?

 I think `TaskCondition` is not a great name so we might want to change that as well.

**Comment by Drvi** [comment]
This functionality now lives in ChunkedBase.jl
